version: '3.8'

services:
  web:
    build: ../transferfoot-api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: jp
      POSTGRES_PASSWORD: giveM3tw3ntyInThisPr0j3ct
      POSTGRES_DB: footdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
